.pragma library

// Generated by tools/gen.py. Do not edit by hand.
var groups = [
  {
    "title": "Appearance",
    "items": [
      {
        "key": "colorMode",
        "label": "Colors",
        "kind": "enum",
        "fallback": "theme",
        "options": [
          "theme",
          "custom",
          "mono",
          "category"
        ],
        "labels": {
          "theme": "Follow theme",
          "custom": "My color",
          "mono": "Monochrome",
          "category": "By category"
        },
        "hint": "Follow theme matches your bar. My color uses the accent below. Monochrome removes every hue. By category tints each category differently."
      },
      {
        "key": "accentColor",
        "label": "My accent color",
        "kind": "color",
        "fallback": "#ff6a1f",
        "hint": "Pick one, or type a hex like #ff6a1f.",
        "presets": [
          "#ff6a1f",
          "#7aa2f7",
          "#bb9af7",
          "#7dcfff",
          "#9ece6a",
          "#e0af68",
          "#f7768e",
          "#c0caf5"
        ],
        "when": [
          {
            "key": "colorMode",
            "is": [
              "custom"
            ]
          }
        ]
      },
      {
        "key": "cardStyle",
        "label": "Card style",
        "kind": "enum",
        "fallback": "soft",
        "options": [
          "soft",
          "outline",
          "flat"
        ],
        "labels": {
          "soft": "Soft",
          "outline": "Outline",
          "flat": "Flat"
        },
        "hint": "Soft fills cards lightly, outline draws a border only, flat has neither."
      },
      {
        "key": "density",
        "label": "Spacing",
        "kind": "enum",
        "fallback": "comfortable",
        "options": [
          "compact",
          "comfortable",
          "spacious"
        ],
        "labels": {
          "compact": "Compact",
          "comfortable": "Comfortable",
          "spacious": "Spacious"
        },
        "hint": "How much air there is between things."
      },
      {
        "key": "cornerRadius",
        "label": "Roundness",
        "kind": "int",
        "fallback": 4,
        "min": 0,
        "max": 20,
        "step": 2,
        "divisor": 1,
        "decimals": 0,
        "hint": "0 is square, 20 is very round."
      },
      {
        "key": "frame",
        "label": "Window outline",
        "kind": "bool",
        "fallback": true,
        "hint": "A thin accent-colored outline around the whole manager."
      },
      {
        "key": "fontScale",
        "label": "Text size",
        "kind": "int",
        "fallback": 100,
        "min": 80,
        "max": 150,
        "step": 5,
        "divisor": 100,
        "decimals": 2,
        "hint": "1 is normal, 1.25 is a quarter bigger."
      },
      {
        "key": "surfaceTint",
        "label": "Window tint",
        "kind": "int",
        "fallback": 6,
        "min": 0,
        "max": 30,
        "step": 1,
        "divisor": 1,
        "decimals": 0,
        "hint": "How much of the accent color washes over the window."
      },
      {
        "key": "showPreviews",
        "label": "Show screenshots",
        "kind": "bool",
        "fallback": true,
        "hint": "Loads preview images from plugins.omarchy.org. Turn off to stay fully offline for images."
      }
    ]
  },
  {
    "title": "Window",
    "items": [
      {
        "key": "windowWidth",
        "label": "Window width",
        "kind": "int",
        "fallback": 1040,
        "min": 640,
        "max": 1600,
        "step": 20,
        "divisor": 1,
        "decimals": 0,
        "hint": "How wide the manager opens."
      },
      {
        "key": "windowHeight",
        "label": "Window height",
        "kind": "int",
        "fallback": 700,
        "min": 420,
        "max": 1100,
        "step": 20,
        "divisor": 1,
        "decimals": 0,
        "hint": "How tall the manager opens."
      },
      {
        "key": "openAs",
        "label": "Open as",
        "kind": "enum",
        "fallback": "panel",
        "options": [
          "panel",
          "window"
        ],
        "labels": {
          "panel": "Bar panel",
          "window": "Own window"
        },
        "hint": "Where the bar button opens the manager. You can always pop it out or dock it back from the header."
      },
      {
        "key": "viewMode",
        "label": "Layout",
        "kind": "enum",
        "fallback": "split",
        "options": [
          "split",
          "grid",
          "list",
          "compact"
        ],
        "labels": {
          "split": "List + stage",
          "grid": "Cards",
          "list": "List",
          "compact": "Compact"
        },
        "hint": "List + stage keeps a big preview of the selected plugin beside the list. Cards show screenshots, list fits the most, compact is a dense table-like view."
      },
      {
        "key": "columns",
        "label": "Card columns",
        "kind": "enum",
        "fallback": "auto",
        "options": [
          "auto",
          "1",
          "2",
          "3",
          "4"
        ],
        "labels": {
          "auto": "Auto",
          "1": "1",
          "2": "2",
          "3": "3",
          "4": "4"
        },
        "hint": "Auto fits as many as the window allows.",
        "when": [
          {
            "key": "viewMode",
            "is": [
              "grid"
            ]
          }
        ]
      },
      {
        "key": "filtersPanel",
        "label": "Filters sidebar",
        "kind": "enum",
        "fallback": "left",
        "options": [
          "left",
          "hidden"
        ],
        "labels": {
          "left": "Shown",
          "hidden": "Hidden"
        },
        "hint": "Hide it for a cleaner look. Search still works."
      }
    ]
  },
  {
    "title": "Browse",
    "items": [
      {
        "key": "defaultSource",
        "label": "Start on",
        "kind": "enum",
        "fallback": "community",
        "options": [
          "community",
          "builtin",
          "all"
        ],
        "labels": {
          "community": "Community",
          "builtin": "Built-in",
          "all": "Everything"
        },
        "hint": "Which plugins you see first when the window opens."
      },
      {
        "key": "defaultSort",
        "label": "Sort by",
        "kind": "enum",
        "fallback": "newest",
        "options": [
          "newest",
          "listed",
          "updated",
          "fresh",
          "hearts",
          "stars",
          "views",
          "rated",
          "az"
        ],
        "labels": {
          "newest": "Newly uploaded",
          "listed": "As listed",
          "updated": "Recently upgraded",
          "fresh": "New or upgraded",
          "hearts": "Most hearts",
          "stars": "Most stars",
          "views": "Most viewed",
          "rated": "Best install rate",
          "az": "A to Z"
        },
        "hint": "Newly uploaded = first listed. As listed = the order the catalog feed returns them in (matches the website's default view). Recently upgraded = latest update. New or upgraded = whichever is most recent."
      },
      {
        "key": "recencyScope",
        "label": "Recency filter looks at",
        "kind": "enum",
        "fallback": "either",
        "options": [
          "either",
          "added",
          "updated"
        ],
        "labels": {
          "either": "Uploaded or upgraded",
          "added": "Uploaded",
          "updated": "Upgraded"
        },
        "hint": "Used together with the time window below.",
        "when": [
          {
            "key": "recencyDays",
            "is": [
              "7",
              "30",
              "90",
              "365"
            ]
          }
        ]
      },
      {
        "key": "recencyDays",
        "label": "Only show from the last",
        "kind": "enum",
        "fallback": "any",
        "options": [
          "any",
          "7",
          "30",
          "90",
          "365"
        ],
        "labels": {
          "any": "Any time",
          "7": "Week",
          "30": "Month",
          "90": "3 months",
          "365": "Year"
        },
        "hint": "Hide plugins that have not been uploaded or upgraded recently."
      },
      {
        "key": "verifiedOnly",
        "label": "Verified only",
        "kind": "bool",
        "fallback": false,
        "hint": "Hide plugins without the Verified badge."
      },
      {
        "key": "hideInstalled",
        "label": "Hide installed",
        "kind": "bool",
        "fallback": false,
        "hint": "Keep plugins you already have out of Browse."
      },
      {
        "key": "showCounts",
        "label": "Show counts",
        "kind": "bool",
        "fallback": true,
        "hint": "Numbers next to categories and tags."
      },
      {
        "key": "newBadgeDays",
        "label": "Call it New for",
        "kind": "int",
        "fallback": 14,
        "min": 1,
        "max": 60,
        "step": 1,
        "divisor": 1,
        "decimals": 0,
        "hint": "Days a plugin keeps its New badge after upload."
      }
    ]
  },
  {
    "title": "Catalog",
    "items": [
      {
        "key": "catalogUrl",
        "label": "Catalog address",
        "kind": "string",
        "fallback": "https://plugins.omarchy.org/catalog.json",
        "hint": "Where the plugin list comes from. Must start with https://.",
        "presets": []
      },
      {
        "key": "refreshHours",
        "label": "Refresh every",
        "kind": "int",
        "fallback": 1,
        "min": 1,
        "max": 168,
        "step": 1,
        "divisor": 1,
        "decimals": 0,
        "hint": "Hours between automatic checks. An unchanged catalog costs a tiny request, not a full download."
      },
      {
        "key": "refreshOnOpen",
        "label": "Refresh when opened",
        "kind": "bool",
        "fallback": true,
        "hint": "Check for a newer catalog every time the window opens. Cheap when nothing changed."
      },
      {
        "key": "checkUpdates",
        "label": "Look for updates",
        "kind": "bool",
        "fallback": true,
        "hint": "Compare installed versions with the catalog and show an Updates tab."
      }
    ]
  },
  {
    "title": "Safety",
    "items": [
      {
        "key": "confirmInstall",
        "label": "Ask before installing",
        "kind": "bool",
        "fallback": true,
        "hint": "Plugins run as unsandboxed code in your shell, so a confirmation is shown first."
      },
      {
        "key": "confirmRemove",
        "label": "Ask before removing",
        "kind": "bool",
        "fallback": true,
        "hint": "Confirm before a plugin is removed."
      },
      {
        "key": "allowUnverified",
        "label": "Allow unverified plugins",
        "kind": "bool",
        "fallback": true,
        "hint": "Off blocks install buttons for anything without the Verified badge."
      },
      {
        "key": "enableAfterInstall",
        "label": "Enable after install",
        "kind": "bool",
        "fallback": true,
        "hint": "Turn a plugin on as soon as it is installed."
      },
      {
        "key": "showSecurityNote",
        "label": "Show the security note",
        "kind": "bool",
        "fallback": true,
        "hint": "A short reminder in the plugin details."
      }
    ]
  },
  {
    "title": "Bar",
    "items": [
      {
        "key": "barDisplay",
        "label": "Bar button shows",
        "kind": "enum",
        "fallback": "both",
        "options": [
          "icon",
          "text",
          "both"
        ],
        "labels": {
          "icon": "Icon",
          "text": "Text",
          "both": "Both"
        },
        "hint": "What the button on the bar looks like."
      },
      {
        "key": "barText",
        "label": "Bar button text",
        "kind": "string",
        "fallback": "Plugins",
        "hint": "Used when text is shown.",
        "presets": [
          "Plugins",
          "Store",
          "Add-ons"
        ],
        "when": [
          {
            "key": "barDisplay",
            "is": [
              "text",
              "both"
            ]
          }
        ]
      },
      {
        "key": "showBadge",
        "label": "Update badge",
        "kind": "bool",
        "fallback": true,
        "hint": "Show how many plugin updates are waiting next to the button."
      },
      {
        "key": "middleClick",
        "label": "Middle click",
        "kind": "enum",
        "fallback": "refresh",
        "options": [
          "refresh",
          "none"
        ],
        "labels": {
          "refresh": "Refresh catalog",
          "none": "Nothing"
        },
        "hint": "What clicking the bar button with the middle mouse button does."
      }
    ]
  }
];

var defaults = {
  "colorMode": "theme",
  "accentColor": "#ff6a1f",
  "cardStyle": "soft",
  "density": "comfortable",
  "cornerRadius": 4,
  "frame": true,
  "fontScale": 100,
  "surfaceTint": 6,
  "showPreviews": true,
  "windowWidth": 1040,
  "windowHeight": 700,
  "openAs": "panel",
  "viewMode": "split",
  "columns": "auto",
  "filtersPanel": "left",
  "defaultSource": "community",
  "defaultSort": "newest",
  "recencyScope": "either",
  "recencyDays": "any",
  "verifiedOnly": false,
  "hideInstalled": false,
  "showCounts": true,
  "newBadgeDays": 14,
  "catalogUrl": "https://plugins.omarchy.org/catalog.json",
  "refreshHours": 1,
  "refreshOnOpen": true,
  "checkUpdates": true,
  "confirmInstall": true,
  "confirmRemove": true,
  "allowUnverified": true,
  "enableAfterInstall": true,
  "showSecurityNote": true,
  "barDisplay": "both",
  "barText": "Plugins",
  "showBadge": true,
  "middleClick": "refresh"
};
